=== Misk23/XML/XML_tim31/src/main/resources/data/XSD/ScientificPublication.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/XML/ScientificPublication"
    xmlns:publ="http://www.ftn.uns.ac.rs/XML/ScientificPublication">

    <xs:element name="scientificPublication">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="metadata">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element maxOccurs="1" name="authors">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="authorUsername" type="xs:string"
                                            maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="keywords"
                                type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" name="chapter">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element maxOccurs="unbounded" name="paragraph">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="text" type="xs:string"/>
                                        <xs:element name="citation">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  name="authorNames" type="xs:string"/>
                                                  <xs:element name="year" type="xs:positiveInteger"/>
                                                  <xs:element name="text" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:integer"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="reference">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="authorNames" type="xs:string"/>
                            <xs:element name="publicationTitle" type="xs:string"/>
                            <xs:element name="year" type="xs:positiveInteger"/>
                            <xs:element name="url" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="citationId" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="publicationId" type="xs:string"/>
            <xs:attribute name="submissionDate" type="xs:date"/>
            <xs:attribute name="language" type="xs:string"/>
            <xs:attribute default="submitted" name="status">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="reviewing"/>
                        <xs:enumeration value="revising"/>
                        <xs:enumeration value="withdrawn"/>
                        <xs:enumeration value="rejected"/>
                        <xs:enumeration value="accepted"/>
                        <xs:enumeration value="submitted"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Misk23/XML/XML_tim31/src/main/resources/data/publicationFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ScientificPublication.xsl"?>
<sp:scientificPublication xmlns:sp="http://www.ftn.uns.ac.rs/XML/ScientificPublication" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:pred="http://www.ftn.uns.ac.rs/rdf/publication/predicate/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/XML/ScientificPublication file:/C:/Users/USER/Desktop/xml_projekat/XML/XML_tim31/src/main/resources/data/XSD/ScientificPublication.xsd" publicationId="publicationId1" submissionDate="2018-05-04" language="srpski" status="accepted">
    <sp:metadata>
        <sp:title property="pred:title" datatype="xs:string">Agilne metodologije u softverskom inzenjerstvu</sp:title>
        <sp:authors>
            <sp:authorUsername property="pred:authorUsername" datatype="xs:string">marko70</sp:authorUsername>
        </sp:authors>
        <sp:keywords property="pred:keywords" datatype="xs:string">java 1</sp:keywords>
        <sp:keywords property="pred:keywords" datatype="xs:string">programiranje 1</sp:keywords>
        <sp:keywords property="pred:keywords" datatype="xs:string">agilnost 1</sp:keywords>
    </sp:metadata>
    <sp:chapter>
        <sp:title property="pred:chapterTitle" datatype="xs:string">Uvod u agilne metodologije 1</sp:title>
        <sp:paragraph>
            <sp:text property="pred:text" datatype="xs:string">tekst 1 o uvodu u agilne metodologije primenjene u softverskom inzenjerstvu</sp:text>
        </sp:paragraph>
        <sp:paragraph>
            <sp:text property="pred:text" datatype="xs:string">tekst 2 o uvodu u agilne metodologije primenjene u softverskom inzenjerstvu</sp:text>
        </sp:paragraph>
    </sp:chapter>
    <sp:chapter>
        <sp:title property="pred:chapterTitle" datatype="xs:string">Napredni koncepti agilnog razvoja softvera</sp:title>
        <sp:paragraph>
            <sp:text property="pred:text" datatype="xs:string">tekst o naprednim tehnikama razvoja softvera</sp:text>
        </sp:paragraph>
        <sp:paragraph>
            <sp:text property="pred:text" datatype="xs:string">tekst koji je citiranc0</sp:text>
            <sp:citation id="0"/>
        </sp:paragraph>
    </sp:chapter>
    <sp:reference citationId="0">
        <sp:authorNames property="pred:authorOfCitation" datatype="xs:string">Marko</sp:authorNames>
        <sp:authorNames property="pred:authorOfCitation" datatype="xs:string">Markovic</sp:authorNames>
        <sp:publicationTitle property="pred:publicationTitle" datatype="xs:string">naslov rada gdje citiran tekst</sp:publicationTitle>
        <sp:year>2019</sp:year>
        <sp:url>link do rada</sp:url>
    </sp:reference>
    <sp:reference citationId="1">
        <sp:authorNames property="pred:authorOfCitation" datatype="xs:string">markomarkovic</sp:authorNames>
        <sp:publicationTitle property="pred:publicationTitle" datatype="xs:string">safasfsafsafa</sp:publicationTitle>
        <sp:year>2017</sp:year>
        <sp:url>sdgfaf</sp:url>
    </sp:reference>
</sp:scientificPublication>

=== Misk23/XML/XML_tim31/src/main/resources/data/XSD/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<scientificPublication xmlns="http://www.ftn.uns.ac.rs/XML/ScientificPublication"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.ftn.uns.ac.rs/XML/ScientificPublication file:/C:/Users/USER/Desktop/xml_projekat/XML/XML_tim31/src/main/resources/data/XSD/ScientificPublication.xsd" publicationId="publicationId2" submissionDate="2016-05-04" language="srpski" status="accepted">
    <metadata>
        <title>Dizajn paterni u javi</title>
        <authors>
            <authorUsername>zoran70</authorUsername>
        </authors>
        <reviewers>
            <reviewerUsername>nikola123</reviewerUsername>
        </reviewers>
        <keywords>java</keywords>
        <keywords>dizajn sabloni</keywords>
        <keywords>arhitektura sistema</keywords>
    </metadata>
    <chapter>
        <title>Osnovni sabloni dizajna</title>
        <paragraph>
            <text>paragraf 1</text>
<!--            <citation id="0">
                <authorNames>authorNames0</authorNames>
                <year>50</year>
                <text>text1</text>
            </citation>-->
        </paragraph>
        <paragraph>
            <text>paragraf 2</text>
            <!--            <citation id="0">
                <authorNames>authorNames0</authorNames>
                <year>50</year>
                <text>text1</text>
            </citation>-->
        </paragraph>
    </chapter>
</scientificPublication>
